name: Docker build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v2
     - name: Build Docker image 
       run: docker build --rm -t test-sample:local .
     - name: Run tests inside the container
       run: docker run test-sample:local